name: Build hw-management release artifacts

on: workflow_dispatch
    
jobs:
  rpm_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install build packages
        run: |
          sudo apt-get install rpm
          sudo apt-get install devscripts build-essential lintian dh-make
      - name: Build deb & rpm packages
        run: |
          debuild -us -uc -d
          cd rpm
          chmod a+x ./gen_rpm.sh
          ./gen_rpm.sh
