# This is an action script to build and attach the packages to a release
name: Build hw-management release artifacts

on: workflow_dispatch
    
jobs:
  rpm_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install build packages
        run: |
          sudo apt-get install rpm
          sudo apt-get install devscripts build-essential lintian dh-make
          
