# This is an action script to build and attach the packages to a release
name: Build hw-management release artifacts

on: 
  release:
    types: [published]
    
jobs:
  rpm_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install build packages
        run: |
          sudo apt-get install rpm
      - name: Build deb & rpm packages
        run: |
          cd rpm
          chmod a+x ./gen_rpm.sh
          ./gen_rpm.sh
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            rpm/*.rpm
